services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Insitaction\DoctrineLoggerBundle\EventListener\DoctrineActivitySubscriber: ~

    Insitaction\DoctrineLoggerBundle\Manager\DoctrineActivityManager: ~

    Insitaction\DoctrineLoggerBundle\Annotation\Loggeable: ~
